CREATE TABLE IF NOT EXISTS public.students (
  sap_id CHAR(11) PRIMARY KEY CHECK (sap_id ~ '^[0-9]{11}$'),
  name VARCHAR(150) NOT NULL,
  student_contact VARCHAR(20),
  gender VARCHAR(10) CHECK (gender IN ('male', 'female')),
  course VARCHAR(20) CHECK (course IN ('BTech', 'MBATech', 'BPharm', 'MPharm', 'Agriculture')),
  year VARCHAR(50) NOT NULL,
  branch VARCHAR(100) NOT NULL,
  batch VARCHAR(50) NOT NULL,
  hostel_block VARCHAR(50),
  room_no VARCHAR(50),
  parent_name VARCHAR(150),
  parent_email VARCHAR(255),
  parent_contact VARCHAR(20),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_students_branch ON public.students (branch);
CREATE INDEX IF NOT EXISTS idx_students_batch ON public.students (batch);
CREATE INDEX IF NOT EXISTS idx_students_parent_email ON public.students (parent_email);

CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  login_id VARCHAR(100) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL CHECK (role IN ('student', 'warden', 'admin', 'security')),
  warden_gender VARCHAR(10) CHECK (warden_gender IN ('male', 'female')),
  name VARCHAR(150) NOT NULL,
  must_change_password BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_users_role_active ON public.users (role, is_active);

CREATE TABLE IF NOT EXISTS public.leave_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sap_id CHAR(11) NOT NULL REFERENCES public.students (sap_id) ON UPDATE CASCADE,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  leave_days INTEGER NOT NULL CHECK (leave_days > 0),
  reason TEXT NOT NULL,
  school VARCHAR(10) CHECK (school IN ('MPSTME', 'SPTM')),
  hostel VARCHAR(40),
  email_from VARCHAR(255),
  email_received_at TIMESTAMPTZ,
  parent_email_matched BOOLEAN NOT NULL DEFAULT FALSE,
  logged_by BIGINT NOT NULL REFERENCES public.users (id) ON UPDATE CASCADE,
  status VARCHAR(30) NOT NULL DEFAULT 'Pending Verification'
    CHECK (status IN ('Pending Verification', 'Granted', 'Rejected', 'Cancelled')),
  pass_token CHAR(64) UNIQUE,
  qr_code_data TEXT,
  granted_by BIGINT REFERENCES public.users (id) ON UPDATE CASCADE,
  granted_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_leave_requests_sap_status ON public.leave_requests (sap_id, status);
CREATE INDEX IF NOT EXISTS idx_leave_requests_status_created ON public.leave_requests (status, created_at);
CREATE INDEX IF NOT EXISTS idx_leave_requests_dates ON public.leave_requests (start_date, end_date);

CREATE TABLE IF NOT EXISTS public.leave_call_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  leave_id BIGINT NOT NULL REFERENCES public.leave_requests (id) ON DELETE CASCADE ON UPDATE CASCADE,
  called_by BIGINT NOT NULL REFERENCES public.users (id) ON UPDATE CASCADE,
  called_number VARCHAR(20) NOT NULL,
  called_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  outcome VARCHAR(20) NOT NULL CHECK (outcome IN ('Confirmed', 'Denied', 'Not Reachable', 'Wrong Person')),
  remarks TEXT
);

CREATE INDEX IF NOT EXISTS idx_leave_call_log_leave ON public.leave_call_log (leave_id);
CREATE INDEX IF NOT EXISTS idx_leave_call_log_called_by ON public.leave_call_log (called_by);

CREATE TABLE IF NOT EXISTS public.audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT REFERENCES public.users (id) ON DELETE SET NULL ON UPDATE CASCADE,
  action VARCHAR(100) NOT NULL,
  entity VARCHAR(100) NOT NULL,
  entity_id BIGINT,
  details JSONB,
  ip VARCHAR(45),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_audit_user_id ON public.audit_log (user_id);
CREATE INDEX IF NOT EXISTS idx_audit_entity ON public.audit_log (entity, entity_id);

CREATE TABLE IF NOT EXISTS public.app_sessions (
  session_id VARCHAR(128) PRIMARY KEY,
  session_data TEXT NOT NULL,
  expires_at BIGINT NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_app_sessions_expires ON public.app_sessions (expires_at);
